measurement:
  operator:
    name: tomography
    img_size: 256
    angles: 180

  noise:
    name: poisson
    rate: 0.2

conditioning:
  method: ps_prox
  params:
    tau: 0.2  

data:
  name: ffhq
  root: ./data/samples/

results:
  name: tomo_5